#! /bin/bash

set -e
set -u

if [[ $# -ne 1 ]] ; then
    echo "Usage: $0 <shader.list>" >&2
    exit 1
fi

SHADER_LIST="$1"

grep -vE '^[[:blank:]]*(#|$)' "${SHADER_LIST}" |
    sort -k2 |
    awk '{ print $1; }'
