#! /usr/bin/env python3

from __future__ import unicode_literals, print_function
import sys
import json

if sys.version_info < (3,):
    import codecs
    import locale
    sys.stdout = codecs.getwriter(locale.getpreferredencoding())(sys.stdout)

input_data = sys.stdin.read()
json_data = json.loads(input_data)
print(json_data["code"])
